package com.myspace;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TimerCleaner implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TimerCleaner() {
    }




}