package com.myspace;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TimerCleaner implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    static final String ETS_JNDI_NAME = "java:module/EJBTimerScheduler";
    static final String JOB_HANDLE_CLASS_NAME = "org.drools.core.time.JobHandle";

    public TimerCleaner() {
    }




}